anchor: Productos Personalizados con Musgo Preservado
title: Productos
color: dark
image: logo-alt-white.svg
bg: videos/entremusgo-decoracion.mp4
size: sm
description: |
  En ENTREMUSGO, cada pieza que ofrecemos es una invitación a experimentar la belleza y el detalle en su máxima expresión. Nuestra selección exclusiva de productos está cuidadosamente diseñada para ofrecer no solo elementos decorativos, sino experiencias que enriquezcan tu espacio y vida.
more:
  full_screen: true
  image_min: 18
  image_max: 18
  parallax: true
  # align: left
