id: productos
bg: productos/personalizados/2023-10-13--11-16-21.jpg
color: white
rows:
- type: columns
  design:
    num: 3
    ratio: 3x4
    button: hide
    card: true
  items:
  - image: productos/bonsais/2023-10-13--10-41-34.jpg
    title: Bonsais
    link: '#bonsais'
  - image: productos/espejos/2023-10-13--10-48-00.jpg
    title: Espejos
    link: '#espejos'
  - image: productos/personalizados/2023-10-13--10-30-17.jpg
    title: Personalizados
    link: '#personalizados'
