title: Espejos
rows:
- type: gallery
  design:
    num: 2
    alt: true
    wrap: false
    gap: true
    cover: true
    grayscale: false
    button: hide
  images:
  - productos/espejos/2023-09-23--19-21-28.jpg
  - productos/espejos/2023-09-23--19-22-19.jpg
  - productos/espejos/2023-10-13--10-47-06.jpg
  - productos/espejos/2023-10-13--10-48-00.jpg
  - productos/espejos/2023-10-13--10-50-03.jpg
